# grant privilege super user 
sudo: required

# tell to use docker service in travis
services:
  - docker

# before install build images
before_install:
  - docker build -t forderation/docker-react -f Dockerfile.dev .

# CI true to force Jest to run in CI-mode 
script:
 - docker run -e CI=true forderation/docker-react npm run test
