FROM node:alpine

WORKDIR '/app'

COPY package.json .

# to enable npm perform on verbose
# RUN npm install --loglevel verbose

RUN npm install --loglevel verbose

COPY . .

CMD ["npm", "run", "start"]